# Generated by Django 4.2.7 on 2023-11-30 21:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import userprofile.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images', validators=[userprofile.validators.validate_file_size])),
                ('cover_pic', models.ImageField(blank=True, null=True, upload_to='images', validators=[userprofile.validators.validate_file_size])),
                ('bio', models.TextField(blank=True, max_length=150, null=True)),
                ('location', models.CharField(blank=True, max_length=45, null=True)),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name=django.core.validators.MaxValueValidator(999999999999999999))),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('link1', models.URLField(blank=True, null=True)),
                ('link2', models.URLField(blank=True, null=True)),
                ('link3', models.URLField(blank=True, null=True)),
                ('link4', models.URLField(blank=True, null=True)),
                ('link5', models.URLField(blank=True, null=True)),
                ('shop_info', models.TextField(blank=True, max_length=2000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
