# Generated by Django 4.2.7 on 2023-11-30 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_usersave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersave',
            old_name='to_post',
            new_name='to_user',
        ),
    ]
