# Generated by Django 4.2.7 on 2023-12-06 01:07

from django.db import migrations, models
import userprofile.validators


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shop_theme1',
            field=models.CharField(default='#ffbdbd', max_length=7, validators=[userprofile.validators.hex_code_validator]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shop_theme2',
            field=models.CharField(default='#ffeded', max_length=7, validators=[userprofile.validators.hex_code_validator]),
        ),
    ]
