# Generated by Django 4.2.7 on 2023-12-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_userprofile_shop_theme1_userprofile_shop_theme2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
