# Generated by Django 4.2.7 on 2023-12-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_gallerypost_title_shoppost'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerypost',
            name='priority',
            field=models.CharField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=1, max_length=10),
        ),
    ]
