# Generated by Django 4.2.7 on 2023-12-02 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_gallerypost_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypost',
            name='priority',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000)]),
        ),
    ]
