# Generated by Django 4.2.7 on 2023-12-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_gallerypost_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppost',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
