# Generated by Django 4.2.7 on 2023-12-05 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_shoppost_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppost',
            name='priority',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000)]),
        ),
    ]
