# Generated by Django 4.2.7 on 2023-12-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_shoppost_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppost',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
